name: clean_framework
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 0.2.5+1
homepage: https://github.com/MattHamburger/clean_framework

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  either_option: ^1.0.6
  equatable: ^1.2.5
  http: ^0.12.2
  meta: ^1.2.4
  provider: ^4.3.2+2

dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.3

